### ISSUE TITLE
Bump fast-json-stringify dependency to 4.1.0

### ISSUE THREAD

**Issue by zedeus** [fastify/fast-json-stringify-compiler#12]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.0.1

### Plugin version

3.0.0

### Node.js version

16.14.2

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Unrelated

### Description

In https://github.com/fastify/fastify/commit/cf46dea8b21fbc2ecac94f56a6119d399b11167a a new fast-json-stringify version is used but only as a dev dependency. I have an older project upgraded to Fastify 4.0.1, but the fast-json-stringify version in my package-lock remained at 4.0.0 instead of 4.1.0, so bumping the version here seems appropriate.

### Steps to Reproduce

Upgrading a project with a lock made prior to the 4.1.0 release.

**Comment by climba03003** [comment]
Remove the `package-lock.json` and install again.
Or use `npm update` to fetch latest version.

**Comment by zedeus** [comment]
That's generally a bad idea: https://stackoverflow.com/questions/54124033/deleting-package-lock-json-to-resolve-conflicts-quickly
It's a production environment with many dependencies, I'd like to avoid unknown side effects. Fastify relies on a new module added to fast-json-stringify 4.1.0, but only pulls in this library which depends on 4.0.0, so the current state cannot be correct.
