### ISSUE TITLE
Compiled serializer is huged because of `serializerState`

### ISSUE THREAD

**Issue by remidewitte** [fastify/fast-json-stringify-compiler#45]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the regression has not already been reported

### Last working version

4.20

### Stopped working in version

4.3.0

### Node.js version

20.x

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

*

### 💥 Regression Report

Every compiled schema contains a stringified version of the schema. Issue is when the schema is huged.
Today it almost kills the advantage of compilation.

It comes from the bump to [v5.7.0](https://github.com/fastify/fast-json-stringify/releases/tag/v5.7.0) of `fast-json-stringify`.
And to be specific if comes from : https://github.com/fastify/fast-json-stringify/pull/617.

It seems that this getState() of the serializer is never used.

### Steps to Reproduce

```ts
async function main() {
  const app = fastify({
    exposeHeadRoutes: false,
    jsonShorthand: false,
    schemaController: {
      compilersFactory: {
        buildSerializer: writeSerializerFactory,
      },
    },
    logger: {
      level: 'debug'
    }
  });

  addAllSchemas(app);

  await app.register(async api => {
    api.register(... all handlers ...)
  });

  await app.ready().then(() => {
    app.log.info('Ready, all serializer compiled');
    app.close();
  });
}


export const writeSerializerFactory = StandaloneSerializer({
  readMode: false,
  storeFunction(routeOpts, schemaSerializationCode) {
    if (routeOpts.method === 'HEAD') {
      return;
    }
    writeFileSync(generateSerializerFilePath(routeOps), schemaSerializationCode);
  },
});
```

### Expected Behavior

Why have this `serializerState` ? Is does not seem to be used at all ?

**Comment by ocadoret** [comment]
Since only `rounding` seems to be used in the state, a workaround for me was to make a patch on `fast-json-stringify` using `yarn patch`, making the following change in serializer.js :
```diff
diff --git a/lib/serializer.js b/lib/serializer.js
index 922be35793cd51c173bde24f992b2d98a172a8ee..fd32a6fea53c6b3c1de49b1216d0c540061acba2 100644
--- a/lib/serializer.js
+++ b/lib/serializer.js
@@ -20,7 +20,7 @@ module.exports = class Serializer {
         this.parseInteger = Math.trunc
         break
     }
-    this._options = options
+    this._options = {rounding: options.rounding}
   }
 
   asInteger (i) {
```

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by remidewitte** [comment]
OK, will do.

I guess the PR will be on fast-json-stringify rather than fast-json-stringify-compiler.

**Comment by remidewitte** [comment]
Here it is : https://github.com/fastify/fast-json-stringify/pull/704

**Comment by Fdawgs** [comment]
@remidewitte Would you say your PR resolved this issue?

**Comment by remidewitte** [comment]
Indeed. You can close. Many thanks
