### ISSUE TITLE
Updating for v5

### ISSUE THREAD

**Issue by Gesma94** [fastify/fast-json-stringify-compiler#49]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

👋 I'm Matteo, and would like to work on this.
Coming from Fastify issue #5116 (https://github.com/fastify/fastify/issues/5116)

From what I've understood, I need to:

- Update any NPM dependencies that might be updated
- Update the workflow to use the version 4 of plugins-ci

If there's anything I'm missing, please do let me know

**Comment by gurgunday** [comment]
> From what I've understood, I need to:

Yes! You can run `npx npm-check-updates -u` to update dependencies, and test them on workflow version `v4.1.0`, please use this specific version
